language: node_js
node_js:
  - "8"
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
notifications:
  email: false
script:
  - npm run build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
