language: node_js
node_js:
  - "8"
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "20.12.21"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
